services:
  web:
    build:
      context: .
    container_name: code_chronicle_web
    env_file:
      - .env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=code_chronicle.settings.production
    volumes:
      - staticfiles:/app/staticfiles
    expose:
      - "8000"

  nginx:
    image: nginx:1.27-alpine
    container_name: code_chronicle_nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - staticfiles:/staticfiles:ro

volumes:
  staticfiles:
